name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Install packages
      run: sudo apt-get install -y ocaml ocaml-dune ocaml-odoc menhir libgraphics-ocaml-dev libx11-dev
    - name: Build
      run: dune build
    - name: Test
      run: dune runtest
    - name: Build documentation
      run: |
        sudo apt-get install -y texlive texlive-pictures texlive-latex-extra texlive-lang-french preview-latex-style
        eval $(opam env) && make -C docs website
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy website
        id: deployment
        uses: actions/deploy-pages@v4
