name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install OCaml
      run: sudo apt-get install ocaml
    - name: Build
      run: make
